
 
CREATE TABLE Bank_loan (
    id                    BIGINT          PRIMARY KEY,
    address_state         VARCHAR(10),
    application_type      VARCHAR(20),
    emp_length            VARCHAR(20),
    emp_title             VARCHAR(150),
    grade                 VARCHAR(5),
    home_ownership        VARCHAR(20),
    issue_date            DATE,
    last_credit_pull_date DATE,
    last_payment_date     DATE,
    loan_status           VARCHAR(30),
    next_payment_date     DATE,
    member_id             BIGINT,
    purpose               VARCHAR(50),
    sub_grade             VARCHAR(5),
    term                  VARCHAR(20),
    verification_status   VARCHAR(30),
    annual_income         NUMERIC(15, 2),
    dti                   NUMERIC(10, 4),
    installment           NUMERIC(10, 2),
    int_rate              NUMERIC(10, 4),
    loan_amount           NUMERIC(15, 2),
    total_acc             INT,
    total_payment         NUMERIC(15, 2)
);

SELECT * FROM BANK_LOAN;

-- 1.Total Loan Applications

SELECT COUNT(ID) AS TOTAL_LOAN_APPLICATIONS
FROM BANK_LOAN;

-- 2.MTD Loan Applications

SELECT COUNT(ID) AS MTD_TOTAL_LOAN_APPLICATIONS
FROM BANK_LOAN
WHERE EXTRACT(MONTH FROM ISSUE_DATE) = 12 AND EXTRACT(YEAR FROM ISSUE_DATE) = 2021;

-- 3.PMTD Loan Applications
SELECT COUNT(ID) AS PMTD_TOTAL_LOAN_APPLICATIONS
FROM BANK_LOAN
WHERE EXTRACT(MONTH FROM ISSUE_DATE) = 11 AND EXTRACT(YEAR FROM ISSUE_DATE) = 2021;

-- 4.Total Funded Amount
SELECT SUM(LOAN_AMOUNT) AS TOTAL_FUNDED_AMOUNT
FROM BANK_LOAN;

-- 5.MTD Total Funded Amount
SELECT SUM(LOAN_AMOUNT) AS MTD_TOTAL_FUNDED_APPLICATIONS
FROM BANK_LOAN
WHERE EXTRACT(MONTH FROM ISSUE_DATE) = 12 AND EXTRACT(YEAR FROM ISSUE_DATE) = 2021;

-- 6.PMTD Total Funded Amount
SELECT SUM(LOAN_AMOUNT) AS PMTD_TOTAL_FUNDED_APPLICATIONS
FROM BANK_LOAN
WHERE EXTRACT(MONTH FROM ISSUE_DATE) = 11 AND EXTRACT(YEAR FROM ISSUE_DATE) = 2021;

-- 7.Total Amount Received
SELECT SUM(TOTAL_PAYMENT) AS TOTAL_AMOUNT_COLLECTED
FROM BANK_LOAN;

-- 8.MTD Total Amount Received
SELECT SUM(TOTAL_PAYMENT) AS MTD_TOTAL_AMOUNT_COLLECTED
FROM BANK_LOAN
WHERE EXTRACT(MONTH FROM ISSUE_DATE) = 12 AND EXTRACT(YEAR FROM ISSUE_DATE) = 2021;

-- 9.PMTD Total Amount Received
SELECT SUM(TOTAL_PAYMENT) AS PMTD_TOTAL_AMOUNT_COLLECTED
FROM BANK_LOAN
WHERE EXTRACT(MONTH FROM ISSUE_DATE) = 11 AND EXTRACT(YEAR FROM ISSUE_DATE) = 2021;

-- 10.Average Interest Rate
SELECT ROUND((AVG(INT_RATE) * 100)::NUMERIC,2) AS AVG_INT_RATE
FROM BANK_LOAN

-- 11.MTD Average Interest
SELECT ROUND((AVG(INT_RATE) * 100)::NUMERIC,2) AS MTD_AVG_INT_RATE
FROM BANK_LOAN
WHERE EXTRACT(MONTH FROM ISSUE_DATE) = 12 AND EXTRACT(YEAR FROM ISSUE_DATE) = 2021;

-- 12.PMTD Average Interest
SELECT ROUND((AVG(INT_RATE) * 100)::NUMERIC,2) AS PMTD_AVG_INT_RATE
FROM BANK_LOAN
WHERE EXTRACT(MONTH FROM ISSUE_DATE) = 11 AND EXTRACT(YEAR FROM ISSUE_DATE) = 2021;

-- 13.Avg DTI
SELECT ROUND((AVG(DTI) * 100)::NUMERIC,2) AS AVG_DTI
FROM BANK_LOAN

-- 14.MTD Avg DTI
SELECT ROUND((AVG(DTI) * 100)::NUMERIC,2) AS MTD_AVG_DTI
FROM BANK_LOAN
WHERE EXTRACT(MONTH FROM ISSUE_DATE) = 12 AND EXTRACT(YEAR FROM ISSUE_DATE) = 2021;

-- 15.PMTD Average Interest
SELECT ROUND((AVG(DTI) * 100)::NUMERIC,2) AS PMTD_AVG_DTI
FROM BANK_LOAN
WHERE EXTRACT(MONTH FROM ISSUE_DATE) = 11 AND EXTRACT(YEAR FROM ISSUE_DATE) = 2021;

-- 16.Good Loan Percentage
SELECT 
     (COUNT(CASE WHEN LOAN_STATUS = 'Fully Paid' OR LOAN_STATUS = 'Current' THEN id END) * 100)
	 /
	 COUNT(id) AS GOOD_LOAN_PERCENTAGE
FROM BANK_LOAN

-- 17.Good Loan Applications
SELECT COUNT(ID) AS GOOD_LOAN_APPLICATION
FROM BANK_LOAN
WHERE LOAN_STATUS IN ('Fully Paid','Current')

-- 18.Good Loan Funded Amount
SELECT SUM(LOAN_AMOUNT) AS GOOD_LOAN_FUNDED_AMOUNT
FROM BANK_LOAN
WHERE LOAN_STATUS IN ('Fully Paid','Current')

-- 19.Good Loan Amount Received
SELECT SUM(TOTAL_PAYMENT) AS GOOD_LOAN_AMOUNT_RECEIVED
FROM BANK_LOAN
WHERE LOAN_STATUS IN ('Fully Paid','Current')

-- 20.Bad Loan Percentage
SELECT 
     (COUNT(CASE WHEN LOAN_STATUS = 'Charged Off' THEN id END) * 100.0)
	 /
	 COUNT(id) AS BAD_LOAN_PERCENTAGE
FROM BANK_LOAN

-- 21.Bad Loan Applications
SELECT COUNT(ID) AS BAD_LOAN_APPLICATION
FROM BANK_LOAN
WHERE LOAN_STATUS = 'Charged Off'

-- 22.Bad Loan Funded Amount
SELECT SUM(LOAN_AMOUNT) AS BAD_LOAN_FUNDED_AMOUNT
FROM BANK_LOAN
WHERE LOAN_STATUS = 'Charged Off'

-- 23.Good Loan Amount Received
SELECT SUM(TOTAL_PAYMENT) AS BAD_LOAN_AMOUNT_RECEIVED
FROM BANK_LOAN
WHERE LOAN_STATUS = 'Charged Off'


-- LOAN STATUS

SELECT LOAN_STATUS,
       COUNT(ID) AS TOTAL_LOAN_APPLICATION,
	   SUM(LOAN_AMOUNT) AS TOTAL_FUNDED_AMOUNT,
	   SUM(TOTAL_PAYMENT) AS TOTAL_AMOUNT_RECEIVED,
	   ROUND((AVG(INT_RATE) * 100)::NUMERIC,2) AS TOTAL_INT_RATE_PERCENTAGE,
	   ROUND((AVG(DTI) * 100)::NUMERIC,2) AS TOTAL_DTI_PERCENTAGE
	   
FROM BANK_LOAN
GROUP BY LOAN_STATUS

-- MTD LOAN STATUS

SELECT LOAN_STATUS,
       
	   SUM(LOAN_AMOUNT) AS MTD_TOTAL_FUNDED_AMOUNT,
	   SUM(TOTAL_PAYMENT) AS MTD_TOTAL_AMOUNT_RECEIVED
	      
FROM BANK_LOAN
WHERE EXTRACT(MONTH FROM ISSUE_DATE) = 12 AND EXTRACT(YEAR FROM ISSUE_DATE) = 2021
GROUP BY LOAN_STATUS

-- MONTH
SELECT EXTRACT(MONTH FROM ISSUE_DATE) AS MONTH_NUMBER,
       TO_CHAR(ISSUE_DATE, 'Month') AS MONTH_NAME,
       COUNT(ID) AS TOTAL_LOAN_APPLICATION,
	   SUM(LOAN_AMOUNT) AS TOTAL_FUNDED_AMOUNT,
	   SUM(TOTAL_PAYMENT) AS TOTAL_AMOUNT_RECEIVED
FROM BANK_LOAN
GROUP BY EXTRACT(MONTH FROM ISSUE_DATE),TO_CHAR(ISSUE_DATE, 'Month') 
ORDER BY EXTRACT(MONTH FROM ISSUE_DATE)


-- STATE
SELECT ADDRESS_STATE AS STATE,
       COUNT(ID) AS TOTAL_LOAN_APPLICATION,
	   SUM(LOAN_AMOUNT) AS TOTAL_FUNDED_AMOUNT,
	   SUM(TOTAL_PAYMENT) AS TOTAL_AMOUNT_RECEIVED
FROM BANK_LOAN
GROUP BY ADDRESS_STATE
ORDER BY ADDRESS_STATE


-- TERM
SELECT TERM AS TERM,
       COUNT(ID) AS TOTAL_LOAN_APPLICATION,
	   SUM(LOAN_AMOUNT) AS TOTAL_FUNDED_AMOUNT,
	   SUM(TOTAL_PAYMENT) AS TOTAL_AMOUNT_RECEIVED
FROM BANK_LOAN
GROUP BY TERM
ORDER BY TERM

-- EMPLOYEE LENTH
SELECT EMP_LENGTH AS EMPLOYEE_LENGTH,
       COUNT(ID) AS TOTAL_LOAN_APPLICATION,
	   SUM(LOAN_AMOUNT) AS TOTAL_FUNDED_AMOUNT,
	   SUM(TOTAL_PAYMENT) AS TOTAL_AMOUNT_RECEIVED
FROM BANK_LOAN
GROUP BY EMP_LENGTH 
ORDER BY EMP_LENGTH 

-- PURPOSE
SELECT PURPOSE AS LOAN_PURPOSE,
       COUNT(ID) AS TOTAL_LOAN_APPLICATION,
	   SUM(LOAN_AMOUNT) AS TOTAL_FUNDED_AMOUNT,
	   SUM(TOTAL_PAYMENT) AS TOTAL_AMOUNT_RECEIVED
FROM BANK_LOAN
GROUP BY PURPOSE
ORDER BY PURPOSE

-- Grade A PURPOSE
SELECT PURPOSE AS LOAN_PURPOSE,
       COUNT(ID) AS TOTAL_LOAN_APPLICATION,
	   SUM(LOAN_AMOUNT) AS TOTAL_FUNDED_AMOUNT,
	   SUM(TOTAL_PAYMENT) AS TOTAL_AMOUNT_RECEIVED
FROM BANK_LOAN
WHERE GRADE = 'A'
GROUP BY PURPOSE
ORDER BY PURPOSE

-- HOME OWNERSHIP
SELECT HOME_OWNERSHIP AS HOME_OWNERSHIP,
       COUNT(ID) AS TOTAL_LOAN_APPLICATION,
	   SUM(LOAN_AMOUNT) AS TOTAL_FUNDED_AMOUNT,
	   SUM(TOTAL_PAYMENT) AS TOTAL_AMOUNT_RECEIVED
FROM BANK_LOAN
GROUP BY HOME_OWNERSHIP
ORDER BY HOME_OWNERSHIP




















































